// Firebase configuration options.
//
// This is a placeholder file. Replace with actual configuration by running:
// ```bash
// flutterfire configure --project=<your-project-id>
// ```
//
// The real file will be generated by FlutterFire CLI and should NOT be
// committed to version control (add to .gitignore for production).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Placeholder Firebase options.
///
/// Replace this with the output of `flutterfire configure`.
class DefaultFirebaseOptions {
  /// Returns the correct [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions is not configured for '
          '${defaultTargetPlatform.name}. '
          'Run `flutterfire configure` to generate this file.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFgCWgcIFJKLuoiLmu4KTEk84iXQPjAig',
    appId: '1:621727324944:android:9fcd0dc17325c5831fa395',
    messagingSenderId: '621727324944',
    projectId: 'onebytwo-506ac',
    storageBucket: 'onebytwo-506ac.firebasestorage.app',
  );

  /// Placeholder Android options — replace with real values.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKW9_yhoecA42Q5wd7tQhyMP39cgnnIHA',
    appId: '1:621727324944:ios:7a27e962d4395e171fa395',
    messagingSenderId: '621727324944',
    projectId: 'onebytwo-506ac',
    storageBucket: 'onebytwo-506ac.firebasestorage.app',
    iosBundleId: 'com.onebytwo.oneByTwo',
  );

  /// Placeholder iOS options — replace with real values.
}
