// Firebase configuration options.
//
// This is a placeholder file. Replace with actual configuration by running:
// ```bash
// flutterfire configure --project=<your-project-id>
// ```
//
// The real file will be generated by FlutterFire CLI and should NOT be
// committed to version control (add to .gitignore for production).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Placeholder Firebase options.
///
/// Replace this with the output of `flutterfire configure`.
class DefaultFirebaseOptions {
  /// Returns the correct [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions is not configured for '
          '${defaultTargetPlatform.name}. '
          'Run `flutterfire configure` to generate this file.',
        );
    }
  }

  /// Placeholder Android options — replace with real values.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER-API-KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'one-by-two-placeholder',
    storageBucket: 'one-by-two-placeholder.appspot.com',
  );

  /// Placeholder iOS options — replace with real values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER-API-KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'one-by-two-placeholder',
    storageBucket: 'one-by-two-placeholder.appspot.com',
    iosBundleId: 'com.onebytwo.oneByTwo',
  );
}
